### ISSUE TITLE
General "top-level" procedure for building toolchain?

### ISSUE THREAD

**Issue by tkchia** [the-grue/OpenDC#1]
Hello @the-grue,

May I know the general procedure you are using (which batch files to run first, etc.) to build the DeSmet C toolchain?

And, is it necessary to use an older version of DeSmet C to bootstrap a newer version?

Thank you!

**Comment by the-grue** [comment]
Good afternoon @tkchia !  I haven't touched this code in awhile so I'll need to re-familiarize myself with what I did.  I am pretty sure I left it in a state where the binaries in the distribution should be able to build all of the code.  As such, I don't think there is a specific order to build everything.

I'll poke around it when I get some time and reply with a follow-up.

Jim

**Comment by the-grue** [comment]
Ok, it doesn't appear that I wrote a top-level build procedure.  It looks like I hand built all of the elements and then consolidated them into a package.  I'll consider this a feature request, and a good one, and will work on it in the near future.

**Comment by the-grue** [comment]
Please see latest commit.  Thank you for the feedback!

**Comment by tkchia** [comment]
Hello @the-grue,

Thank you!  I think I can now bootstrap a new DeSmet C toolchain from the previously pre-compiled binaries in `bin/distros/`.

I will see how I can further improve the toolchain.  ☺

Thank you!
